### ISSUE TITLE
Problem in running

### ISSUE THREAD

**Issue by arnabsinha** [unitreerobotics/UnitreecameraSDK#24]
I have followed the following steps (as described in one of the issue),
1. sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
2. sudo apt-get install gstreamer1.0-plugins-bad
3. sudo apt-get update
4. sudo apt-get install libudev1
5. sudo apt-get install libudev1 libudev-dev
6. sudo apt-get install freeglut3-dev
After this I followed the following:
1. mkdir build && cd build
2. make
3. cd ..
4. ./bins/example_getRawFrame
But got the following error
```
[ WARN:0] global ./modules/videoio/src/cap_gstreamer.cpp (1100) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
Read A NULL File, Camera CalibParams not loaded!
[UnitreeCameraSDK][ERROR] load tmp file failed, temp file permission error!
[UnitreeCameraSDK][ERROR] This camera cannot get internal parameters!
[UnitreeCameraSDK][ERROR] You should flash the calibration parameters or load it from disk.
Segmentation fault (core dumped)
```

With gdb I ran with the following result:
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe5800640 (LWP 218763)]
[New Thread 0x7fffe4a00640 (LWP 218764)]
[ WARN:0] global ./modules/videoio/src/cap_gstreamer.cpp (1100) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
[Thread 0x7fffe5800640 (LWP 218763) exited]
Read A NULL File, Camera CalibParams not loaded!
[UnitreeCameraSDK][ERROR] load tmp file failed, temp file permission error!
[Detaching after vfork from child process 218765]
[UnitreeCameraSDK][ERROR] This camera cannot get internal parameters!
[UnitreeCameraSDK][ERROR] You should flash the calibration parameters or load it from disk.

Thread 1 "example_getRawF" received signal SIGSEGV, Segmentation fault.
0x00007ffff73fd714 in cv::UMat::release() () from /lib/x86_64-linux-gnu/libopencv_core.so.4.5d
(gdb) bt
#0  0x00007ffff73fd714 in cv::UMat::release() () at /lib/x86_64-linux-gnu/libopencv_core.so.4.5d
#1  0x00007ffff7ec79d0 in cv::VideoCapture::read(cv::_OutputArray const&) () at /lib/x86_64-linux-gnu/libopencv_videoio.so.4.5d
#2  0x00007ffff7ec772a in cv::VideoCapture::operator>>(cv::UMat&) () at /lib/x86_64-linux-gnu/libopencv_videoio.so.4.5d
#3  0x00005555555819e1 in StereoCamera::setRawFrameSize(cv::Size_<int>) ()
#4  0x000055555557a177 in UnitreeCamera::UnitreeCamera(int) ()
#5  0x0000555555576f3e in main ()
(gdb) bt full
#0  0x00007ffff73fd714 in cv::UMat::release() () at /lib/x86_64-linux-gnu/libopencv_core.so.4.5d
#1  0x00007ffff7ec79d0 in cv::VideoCapture::read(cv::_OutputArray const&) () at /lib/x86_64-linux-gnu/libopencv_videoio.so.4.5d
#2  0x00007ffff7ec772a in cv::VideoCapture::operator>>(cv::UMat&) () at /lib/x86_64-linux-gnu/libopencv_videoio.so.4.5d
#3  0x00005555555819e1 in StereoCamera::setRawFrameSize(cv::Size_<int>) ()
#4  0x000055555557a177 in UnitreeCamera::UnitreeCamera(int) ()
#5  0x0000555555576f3e in main ()
```

**Comment by arnabsinha** [comment]
With the command
```
./bins/example_getRawFrame 2
```
I am getting the following:
```
[ WARN:0] global ./modules/videoio/src/cap_gstreamer.cpp (2075) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Internal data stream error.
[ WARN:0] global ./modules/videoio/src/cap_gstreamer.cpp (1053) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global ./modules/videoio/src/cap_gstreamer.cpp (616) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[UnitreeCameraSDK][INFO] Load camera flash parameters OK!
Segmentation fault (core dumped)
```
With "v4l2-ctl -L -d /dev/video2" I am getting the following:
```
User Controls

                     brightness 0x00980900 (int)    : min=-64 max=64 step=1 default=0 value=0
                       contrast 0x00980901 (int)    : min=0 max=95 step=1 default=0 value=0
                     saturation 0x00980902 (int)    : min=0 max=100 step=1 default=64 value=64
                            hue 0x00980903 (int)    : min=-2000 max=2000 step=1 default=0 value=0
        white_balance_automatic 0x0098090c (bool)   : default=1 value=1
                          gamma 0x00980910 (int)    : min=100 max=300 step=1 default=100 value=100
                           gain 0x00980913 (int)    : min=0 max=255 step=1 default=100 value=100
           power_line_frequency 0x00980918 (menu)   : min=0 max=2 default=1 value=1 (50 Hz)
				0: Disabled
				1: 50 Hz
				2: 60 Hz
      white_balance_temperature 0x0098091a (int)    : min=2800 max=6500 step=1 default=4600 value=4600 flags=inactive
                      sharpness 0x0098091b (int)    : min=0 max=7 step=1 default=0 value=0
         backlight_compensation 0x0098091c (int)    : min=0 max=100 step=1 default=48 value=48

Camera Controls

                  auto_exposure 0x009a0901 (menu)   : min=0 max=3 default=3 value=3 (Aperture Priority Mode)
				1: Manual Mode
				3: Aperture Priority Mode
         exposure_time_absolute 0x009a0902 (int)    : min=1 max=10000 step=1 default=156 value=156 flags=inactive
```
```

**Comment by snktsummon** [comment]
Hi @arnabsinha , found any solution?
